{% set name = "pycollo" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycollo-{{ version }}.tar.gz
  sha256: 587a3fc4f0913c56af9409b33ae88bce848b2ba495866588233e15686cb37bd8

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm >=3
  run:
    - casadi >=3.5.5
    - matplotlib-base >=3.3.2
    - numba >=0.51.2
    - numpy >=1.19.1
    - pyproprop >=0.4.10
    - python >={{ python_min }}
    - scipy >=1.5.2
    - sympy >=1.6.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pycollo

about:
  home: https://pypi.org/project/pycollo/
  summary: General-purpose optimal control using direct collocation methods
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brocksam
